### PR TITLE
fix(ansi-to-html): Change ANSI code 21 from bold off to double underline

### LINKED ISSUE #43: Consider changing ANSI code 21 from bold-off to no-op
Currently ANSI code 21 is defined as setting bold off which looks to be somewhat correct historically, but appears to be consistently interpreted as doubly underlined nowadays including even in Linux's console (well it renders as cyan for me, but it does still get toggled off by the ANSI code for underlined off, so I'm assuming that's just a stylist choice due to the rendering limitations)

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**
Resolves #43

Switches ANSI code 21 from bold off to double underline using `<u style='text-decoration-style:double>`. The added test demos how `<ESC>[4mSingle<ESC>[0m <ESC>[21mDouble` gets converted to

```html
<u>Single</u> <u style='text-decoration-style:double'>Double</u>
```

which renders in the browser like so

image

### CODE REVIEW

File: crates/ansi-to-html/fuzz/utils/html_interpreter.rs [hunk 1]
```diff
@@ -190,7 +190,7 @@ impl StylizedText {
 pub struct Styles {
     bold: bool,
     italic: bool,
-    underlined: bool,
+    underlined: Option<Option<Attr>>,
```
Comment (Aloso) [inline crates/ansi-to-html/fuzz/utils/html_interpreter.rs:193]: I don't like nested `Option`s. Can we use the `UnderlineStyle` enum here?

Comment (CosmicHorrorDev) [reply crates/ansi-to-html/fuzz/utils/html_interpreter.rs]: Done and done :tada:

I copied the definition out, but alternatively the original definition could be exposed publicly through a lot of `cfg(fuzzing)`

**Review by Aloso — APPROVED** [review]

**Comment by Aloso** [comment]
Thanks!
